sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

language: php

php:
  - 5.4
  - 7.1

branches:
  only:
    - /.*/
    - master
    - develop

env:
  matrix:
  - WP_VERSION=4.6
  - WP_VERSION=latest
  - WP_VERSION=trunk

before_install:
  - phpenv config-rm xdebug.ini

install:
  - bash .dev/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - composer global require wp-coding-standards/wpcs
  - phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs

script:
  - phpcs --standard=.dev/phpcs.ruleset.xml $(find . -name '*.php')
  - phpunit -c .dev/phpunit.xml.dist

jobs:
  fast_finish: true
  exclude:
    - php: 7.1
      env: WP_VERSION=4.6
    - php: 7.1
      env: WP_VERSION=latest
  include:
    - stage: code coverage
      php: 7.1
      env: WP_VERSION=latest
      before_install: true # skip by returning true
      install:
        - bash .dev/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
        - export PATH="$HOME/.composer/vendor/bin:$PATH"
        - composer config --global github-protocols 'https'
        - composer global require "phpunit/phpunit=5.7.*"
        - composer require satooshi/php-coveralls
      script:
        - phpunit -c .dev/phpunit.xml.dist --coverage-clover .dev/clover.xml
      after_script:
        - travis_retry php vendor/bin/coveralls -v

before_deploy:
  - curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar > /tmp/wp-cli.phar
  - chmod +x /tmp/wp-cli.phar
  - php /tmp/wp-cli.phar package install git@github.com:wp-cli/dist-archive-command.git
  - export RELEASE_FOLDER=reseller-store-settings
  - cp -r ${TRAVIS_BUILD_DIR} /tmp/${RELEASE_FOLDER}
  - mv /tmp/${RELEASE_FOLDER} ${TRAVIS_BUILD_DIR}
  - php /tmp/wp-cli.phar dist-archive ${RELEASE_FOLDER} ${TRAVIS_BUILD_DIR}/${RELEASE_FOLDER}.zip --format=zip --debug

deploy:
  provider: releases
  api_key:
    secure: JwMBerciUmR4rajcTS9uZwNHjRaBqw8eflX7APMovjPgH8HGvt2GtyDh564icrq2fQFlXfuGb6mTFHZhqiA5wRuKlqMCMTXDTJuZ2CE8RUqRA/rTwALZ6u+n4r1IsBMHpmm9qcXyIklrT2D9ImQEOUp2gjvAljV+8W6vqST8XpLHZi7Yj5hozdUR0rkinzDWBhQOA4im1/CK4tqareB3PuCLNmcWj5mQGvt6Yf1Ih5NJA1QyBsXQtmSXdJpq8HNlTWu2+czEx26s8ELRWlfXHrC/DAiFclcsVW1ykNbIvOHNLyEq7b5O9SxAyJfRAPNQ4/6fmFj0hXUJJUXti99N0/062QzPSBZCwDkruzSWZ6sqtlT7jbyZYE+trnFfWXxDILKcfYI0a6c9ms1B7PKssHKNX8aslyf+uv3sIvY/i1vGanw+fDZlc9WcYzbkkZ8253fqr2MjkGI2CMK7vCr4Dy0Mz6SnvJUPzOd77kDlVu4aGQmdNUtRzmFcWibBNI5bZd2LwcEvvvQna1tff6S5H4meta7Y3eAtu3ldAmk/33AICMK8zhRkurg502DCe6uxXRdee0OqTYq9S/XZ92gNJbMhCFqypuOs3dYPjDUNjFcN4rSUt2HTZSvzpQx6Pzk0KI2E77lPHeLOcHrZRQcztgi1cuydjJ4vFDOIliNrNLs=
  file: $RELEASE_FOLDER.zip
  on:
    tags: true
    repo: Resellers/wp-reseller-store-settings
    php: '7.1'
    condition:  $WP_VERSION = latest
  skip_cleanup: true
  overwrite: true
